server:
  port: 4999

spring:
  application:
    name: zuul-gateway-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true

zuul:
  routes:
    stock-query-service:
        path: /api/v1.0/market/stock/**
        url: http://localhost:5001
    stock-command-service:
        path: /api/v1.0/market/stock/**
        url: http://localhost:5000