server:
  port: 5000

spring:
  application:
    name: zuul-gateway-server

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      preferIpAddress: true

zuul:
  routes:
    stock-command-service:
      path: /api/v1.0/market/stock/**
      url: http://localhost:5001
    stock-query-service:
        path: /api/v1.0/market/stock/**
        url: http://localhost:5002
    company-service:
        path: /api/v1.0/market/company/**
        url: http:/localhost:5003